### ISSUE TITLE
求助：请问怎样运行起来这个项目

### ISSUE THREAD

**Issue by dwaynewei** [B1gM8c/PrivacysClub#4]
# 问题
* 个人对前端技术不太懂，因此没有能够运行起来，求助！

# 过程
* 拉到本地之后，`npm install`， `npm run dev` 都没有效果，似乎提示说没有找到 npm 的field
* 直接打开 .html 文件，浏览器里的页面是空白的
* 使用 `node file.js` 也没有能够 运行起来

# 求助
* 请问大佬怎样可以运行起来这个项目的？  希望能够指点迷津，如果不好解释，也请给一个链接，我自己去学习也可以的
* 先谢谢了！！

**Comment by B1gM8c** [comment]
已经更新node版本了~
