### ISSUE TITLE
运行报错，这是咋回事呢

### ISSUE THREAD

**Issue by CQ43** [B1gM8c/PrivacysClub#5]
![image](https://user-images.githubusercontent.com/49177424/135049768-10c81dc1-6191-4dcb-ad09-5094bd533d48.png)

**Comment by CQ43** [comment]
@B1gM8c

**Comment by B1gM8c** [comment]
这个不用运行的 这个是打包好的版本

**Comment by B1gM8c** [comment]
你说的这个是接口问题，已经更新node版本了
